DROP TABLE TMPSALGUIDE CASCADE CONSTRAINTS;
DROP TABLE TMPEMP CASCADE CONSTRAINTS;

CREATE TABLE TMPEMP AS SELECT * FROM EMP;

CREATE TABLE TMPSALGUIDE
( JOB VARCHAR2(9) PRIMARY KEY,
  MINSAL NUMBER(7,2) NOT NULL,
  MAXSAL NUMBER(7,2) );

INSERT INTO TMPSALGUIDE VALUES ('CLERK', 5000, 15000);
INSERT INTO TMPSALGUIDE VALUES ('ANALYST', 10000, 20000);
INSERT INTO TMPSALGUIDE VALUES ('MANAGER', 20000, 40000);
INSERT INTO TMPSALGUIDE VALUES ('SALESMAN', 5000, 30000);
INSERT INTO TMPSALGUIDE VALUES ('PRESIDENT', 50000,'' );

CREATE OR REPLACE TRIGGER TMP_SALARY_CHECK
BEFORE INSERT OR UPDATE OF SAL, JOB
ON TMPEMP
FOR EACH ROW
WHEN (NEW.JOB <> 'PRESIDENT')
DECLARE
    MINSAL NUMBER;
    MAXSAL NUMBER;
BEGIN
    SELECT MINSAL, MAXSAL
    INTO MINSAL, MAXSAL
    FROM TMPSALGUIDE
    WHERE JOB = :NEW.JOB;
    IF (:NEW.SAL < MINSAL OR :NEW.SAL > MAXSAL)
    THEN RAISE_APPLICATION_ERROR(-20601,
        'SALARY ' || :NEW.SAL || ' OUT OF RANGE FOR JOB ' || :NEW.JOB ||
        ' FOR EMPLOYEE ' || :NEW.ENAME);
    END IF;
END;

INSERT INTO TMPEMP ( ENAME, JOB, SAL)
VALUES ('JANE', 'CLERK', 5000);

INSERT INTO TMPEMP (ENAME, JOB, SAL)
VALUES ('JANE', 'CLERK', 4000);
